# Generated by Django 4.2.20 on 2025-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0009_product_product_image1_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_moq',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_icon1',
            field=models.ImageField(blank=True, null=True, upload_to='trusted_icons/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_icon2',
            field=models.ImageField(blank=True, null=True, upload_to='trusted_icons/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_icon3',
            field=models.ImageField(blank=True, null=True, upload_to='trusted_icons/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_icon4',
            field=models.ImageField(blank=True, null=True, upload_to='trusted_icons/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_text1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_text2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_text3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_trusted_text4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
