# Generated by Django 4.2.20 on 2025-06-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesanalysisresult',
            name='platform_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysisresult',
            name='sales_data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='business_analytics.salesdatafile'),
        ),
    ]
