# Generated by Django 4.2.20 on 2025-06-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_analytics', '0002_salesanalysisresult_platform_type_and_more'),
    ]

    operations = [
    ]
