# Generated by Django 5.1.5 on 2025-04-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_websiteproduct_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(help_text='Primary brand color (hex code)', max_length=20)),
                ('secondary_color', models.CharField(help_text='Secondary brand color (hex code)', max_length=20)),
                ('accent_color', models.CharField(help_text='Accent color for highlights (hex code)', max_length=20)),
                ('background_color', models.CharField(help_text='Main background color (hex code)', max_length=20)),
                ('text_color', models.CharField(help_text='Main text color (hex code)', max_length=20)),
                ('link_color', models.CharField(help_text='Link color (hex code)', max_length=20)),
                ('button_color', models.CharField(help_text='Button color (hex code)', max_length=20)),
                ('button_text_color', models.CharField(help_text='Button text color (hex code)', max_length=20)),
                ('header_color', models.CharField(help_text='Header background color (hex code)', max_length=20)),
                ('footer_color', models.CharField(help_text='Footer background color (hex code)', max_length=20)),
                ('is_dark', models.BooleanField(default=False, help_text='Is this a dark theme?')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_family', models.CharField(max_length=100)),
                ('font_type', models.CharField(choices=[('google', 'Google Font'), ('custom', 'Custom Font'), ('system', 'System Font')], default='google', max_length=20)),
                ('url', models.URLField(blank=True, help_text='URL for loading font if not a system font', null=True)),
                ('weights_available', models.CharField(default='400,700', help_text='Comma-separated list of available weights', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='My Website', max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='WebsiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('banner', 'Banner'), ('hero', 'Hero Image'), ('background', 'Background Image'), ('icon', 'Icon'), ('custom', 'Custom Asset')], default='custom', max_length=20)),
                ('file', models.FileField(upload_to='website_assets/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in pixels', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='website.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('logs', models.TextField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='website.website')),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_previews/')),
                ('description', models.TextField(blank=True)),
                ('color_scheme', models.JSONField(default=dict, help_text='JSON containing color scheme information')),
                ('typography', models.JSONField(default=dict, help_text='JSON containing typography settings')),
                ('layout_settings', models.JSONField(default=dict, help_text='JSON containing layout settings')),
                ('component_styles', models.JSONField(default=dict, help_text='JSON containing component styles')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, help_text='Associated template if theme is template-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='website.websitetemplate')),
            ],
        ),
    ]
