# Generated by Django 5.1.5 on 2025-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_websitecolorscheme_websitefont_website_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='last_deployed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
