# Generated by Django 4.2.20 on 2025-06-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apps_is_temporarily_disabled'),
        ('onematrix', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='excluded_apps',
            field=models.ManyToManyField(blank=True, to='app.apps'),
        ),
    ]
