# Generated by Django 4.2.20 on 2025-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_onboardinginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvitation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardinginvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
