# Generated by Django 4.2.20 on 2025-05-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_employeedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardinginvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardinginvitation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department'),
        ),
        migrations.AlterField(
            model_name='onboardinginvitation',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.designation'),
        ),
        migrations.AlterField(
            model_name='onboardinginvitation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.role'),
        ),
        migrations.AlterField(
            model_name='onboardinginvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
