# Generated by Django 4.2.20 on 2025-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_onboardinginvitation_discussion_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvitation',
            name='is_form_completed',
            field=models.BooleanField(default=False),
        ),
    ]
