# Generated by Django 4.2.20 on 2025-05-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_add_is_form_completed_to_onboardinginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvitation',
            name='handbook_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.handbook'),
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='hiring_agreement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.hiringagreement'),
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='hr_policies_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_policies_invitations', to='hr.tandc'),
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='training_material_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.trainingmaterial'),
        ),
    ]
