# Generated by Django 4.2.20 on 2025-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_onboardinginvitation_handbook_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvitation',
            name='additional_documents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
