# Generated by Django 4.2.20 on 2025-05-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_quicknote'),
        ('hr', '0029_onboardinginvitation_additional_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='User.user'),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='User.user'),
        ),
        migrations.AddField(
            model_name='designation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='User.user'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='User.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='User.user'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='User.user'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='User.user'),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='User.user'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbooks', to='User.user'),
        ),
        migrations.AddField(
            model_name='hiringagreement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_agreements', to='User.user'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='User.user'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='User.user'),
        ),
        migrations.AddField(
            model_name='onboardinginvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invitations', to='User.user'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='User.user'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_requests', to='User.user'),
        ),
        migrations.AddField(
            model_name='resignation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='User.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='User.user'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='User.user'),
        ),
        migrations.AddField(
            model_name='tandc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to='User.user'),
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_materials', to='User.user'),
        ),
    ]
