# Generated by Django 4.2.20 on 2025-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_company_user_department_user_designation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
