# Generated by Django 4.2.20 on 2025-05-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_remove_employee_allowances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('last_device_change', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Registered Device',
                'verbose_name_plural': 'Registered Devices',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='DeviceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_device_id', models.CharField(max_length=255)),
                ('new_device_id', models.CharField(max_length=255)),
                ('new_device_info', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_change_requests', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Device Change Request',
                'verbose_name_plural': 'Device Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
