# Generated by Django 4.2.20 on 2025-06-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_registereddevice_devicechangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereddevice',
            name='employee',
        ),
        migrations.DeleteModel(
            name='DeviceChangeRequest',
        ),
        migrations.DeleteModel(
            name='RegisteredDevice',
        ),
    ]
