# Generated by Django 4.2.20 on 2025-06-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_leavepolicy_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='leavepolicyrule',
            name='leave_policy',
        ),
        migrations.RemoveField(
            model_name='leavepolicyrule',
            name='leave_type',
        ),
        migrations.DeleteModel(
            name='EmployeeLeaveConfiguration',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='LeavePolicy',
        ),
        migrations.DeleteModel(
            name='LeavePolicyRule',
        ),
    ]
