# Generated by Django 4.2.20 on 2025-06-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_remove_holiday_company_remove_leavepolicy_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinginvitation',
            name='accepted_offer_letter',
        ),
        migrations.RemoveField(
            model_name='onboardinginvitation',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='onboardinginvitation',
            name='otp_expires_at',
        ),
    ]
