# Generated by Django 4.2.20 on 2025-06-27 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_remove_onboardinginvitation_accepted_offer_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
