# Generated by Django 4.2.20 on 2025-06-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_alter_employeedocument_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedocument',
            old_name='id',
            new_name='document_id',
        ),
    ]
