# Generated by Django 4.2.20 on 2025-06-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_employee_aadhar_number_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_number',
            field=models.FileField(blank=True, null=True, upload_to='hr/employee_documents/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=models.FileField(blank=True, null=True, upload_to='hr/employee_documents/pan/'),
        ),
    ]
