# Generated by Django 4.2.20 on 2025-06-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0044_payouttype_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hr.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payouttype',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payout_types', to='hr.company'),
            preserve_default=False,
        ),
    ]
