# Generated by Django 4.2.20 on 2025-06-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_holiday_company_payouttype_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.company'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.company'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hr.company'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='hr.company'),
        ),
        migrations.AlterField(
            model_name='payouttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_types', to='hr.company'),
        ),
    ]
