# Generated by Django 4.2.20 on 2025-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0046_alter_allowance_company_alter_deduction_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='days_allowed',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='description',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
