# Generated by Django 4.2.20 on 2025-06-27 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_user_is_staff'),
        ('hr', '0047_remove_leavetype_days_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_groups', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveGroupPayout',
            fields=[
                ('leave_group_payout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='hr.leavegroup')),
                ('payout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.payouttype')),
            ],
        ),
    ]
