# Generated by Django 4.2.20 on 2025-06-27 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_leavegroup_leavegrouppayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveGroupRule',
            fields=[
                ('leave_group_rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hr.leavegroup')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveGroupPayout',
        ),
    ]
