# Generated by Django 4.2.20 on 2025-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_leavegrouprule_delete_leavegrouppayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavegroup',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Yearly', max_length=10),
        ),
    ]
