# Generated by Django 4.2.20 on 2025-06-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_employee_bifurcate_salary_employee_gross_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leavegroup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payouts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeePayout',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
