# Generated by Django 4.2.20 on 2025-06-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_remove_group_user_remove_employee_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bifurcate_salary',
        ),
    ]
