# Generated by Django 4.2.20 on 2025-06-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_attendancerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='hr.company'),
        ),
    ]
