# Generated by Django 4.2.20 on 2025-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0056_remove_attendancerule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount to deduct if 'Deduct Amount' is selected.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_arrival_grace_period',
            field=models.TimeField(blank=True, help_text='The latest time an employee can punch in without penalty.', null=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='rule_option',
            field=models.CharField(blank=True, choices=[('deduct_amount', 'Deduct Amount'), ('half_day', 'Half Day')], help_text='Action to take for late arrivals.', max_length=20, null=True),
        ),
    ]
