# Generated by Django 4.2.20 on 2025-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_attendancerule_deduction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_arrival_grace_period',
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_arrival_end_time',
            field=models.TimeField(blank=True, help_text='The end time for the late arrival grace period.', null=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_arrival_start_time',
            field=models.TimeField(blank=True, help_text='The start time for the late arrival grace period.', null=True),
        ),
    ]
