# Generated by Django 4.2.20 on 2025-06-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0058_remove_attendancerule_late_arrival_grace_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_arrival_end_time',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_arrival_start_time',
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_arrival_grace_period_end',
            field=models.TimeField(blank=True, help_text='The end of the grace period for late punch-ins. Optional.', null=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_arrival_grace_period_start',
            field=models.TimeField(blank=True, help_text='The start of the grace period for late punch-ins.', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='hr.company', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='rule_option',
            field=models.CharField(blank=True, choices=[('deduct_amount', 'Deduct Amount'), ('half_day', 'Mark as Half Day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='working_days',
            field=models.CharField(help_text="Comma-separated list of weekdays, e.g., 'Monday,Tuesday,...'", max_length=255),
        ),
    ]
