# Generated by Django 4.2.20 on 2025-06-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_alter_attendancerule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='late_punch_out_time',
            field=models.TimeField(blank=True, help_text='The time for early punch-out.', null=True),
        ),
    ]
