# Generated by Django 4.2.20 on 2025-06-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0060_attendancerule_late_punch_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='late_punch_out_deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='late_punch_out_rule_option',
            field=models.CharField(blank=True, choices=[('deduct_amount', 'Deduct Amount'), ('half_day', 'Mark as Half Day')], max_length=20, null=True),
        ),
    ]
