# Generated by Django 4.2.20 on 2025-06-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_attendancerule_late_punch_out_deduction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerule',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_arrival_grace_period_end',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_arrival_grace_period_start',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_punch_out_deduction_amount',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_punch_out_rule_option',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='late_punch_out_time',
        ),
        migrations.RemoveField(
            model_name='attendancerule',
            name='rule_option',
        ),
        migrations.CreateModel(
            name='LatePunchInRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('rule_option', models.CharField(choices=[('deduct_amount', 'Deduct Amount'), ('half_day', 'Mark as Half Day')], max_length=20)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attendance_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_punch_in_rules', to='hr.attendancerule')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyPunchOutRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('rule_option', models.CharField(choices=[('deduct_amount', 'Deduct Amount'), ('half_day', 'Mark as Half Day')], max_length=20)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attendance_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_punch_out_rules', to='hr.attendancerule')),
            ],
        ),
    ]
