# Generated by Django 4.2.20 on 2025-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='is_temporarily_disabled',
            field=models.BooleanField(default=False, help_text='Set to true to temporarily disable this app for all users.'),
        ),
    ]
