# Generated by Django 4.2.20 on 2025-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apps_is_temporarily_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='url_keyword',
            field=models.CharField(blank=True, help_text="A unique keyword found in this app's URLs, e.g., 'invoicing'.", max_length=100, null=True, unique=True),
        ),
    ]
