# Generated by Django 4.2.20 on 2025-06-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_quicknote'),
        ('trends', '0002_trendsearch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendsearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_searches', to='User.user'),
        ),
    ]
