# Generated by Django 4.2.20 on 2025-06-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trends', '0003_alter_trendsearch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendsearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_searches', to=settings.AUTH_USER_MODEL),
        ),
    ]
