# Generated by Django 4.2.20 on 2025-06-21 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('focus_keywords', models.CharField(blank=True, max_length=255)),
                ('alt_keyword_1', models.CharField(blank=True, max_length=255)),
                ('alt_keyword_2', models.CharField(blank=True, max_length=255)),
                ('product_image_1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image_1_alt', models.CharField(blank=True, max_length=255)),
                ('product_image_2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image_2_alt', models.CharField(blank=True, max_length=255)),
                ('product_image_3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image_3_alt', models.CharField(blank=True, max_length=255)),
                ('product_image_4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image_4_alt', models.CharField(blank=True, max_length=255)),
                ('product_image_5', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image_5_alt', models.CharField(blank=True, max_length=255)),
                ('product_video', models.FileField(blank=True, null=True, upload_to='product_videos/')),
                ('product_description', models.TextField(blank=True, max_length=1000)),
                ('variations', models.JSONField(blank=True, null=True)),
                ('uses', models.TextField(blank=True)),
                ('best_suited_for', models.TextField(blank=True)),
                ('social_media_facebook', models.URLField(blank=True)),
                ('social_media_twitter', models.URLField(blank=True)),
                ('social_media_instagram', models.URLField(blank=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('gst_details', models.CharField(blank=True, max_length=100)),
                ('map_location', models.URLField(blank=True)),
                ('faqs', models.JSONField(blank=True, null=True)),
                ('size_chart', models.FileField(blank=True, null=True, upload_to='size_charts/')),
                ('why_choose_us', models.TextField(blank=True)),
                ('comparison', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Product Details',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
