# Generated by Django 4.2.20 on 2025-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesuggest', '0002_productdetails_updated_at_productdetails_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product_video',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='video_url_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='video_url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='video_url_3',
            field=models.URLField(blank=True),
        ),
    ]
