# Generated by Django 4.2.20 on 2025-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesuggest', '0003_remove_productdetails_product_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description limited to approximately 60 words', max_length=300),
        ),
    ]
