# Generated by Django 4.2.20 on 2025-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesuggest', '0004_productdetails_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
