# Generated by Django 4.2.20 on 2025-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesuggest', '0005_remove_productdetails_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='comparisons',
            field=models.JSONField(blank=True, default=list, help_text="Dynamic comparison data with 'us' and 'others' fields", null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='comparison',
            field=models.TextField(blank=True, help_text='Legacy comparison field - will be migrated to comparisons field'),
        ),
    ]
