# Generated by Django 4.2.20 on 2025-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesuggest', '0006_productdetails_comparisons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeesuggestAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the agreement.', max_length=255)),
                ('content', models.TextField(help_text='The full content of the agreement.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one agreement can be active at a time. Activating this will deactivate others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beesuggest Agreement',
                'verbose_name_plural': 'Beesuggest Agreements',
                'ordering': ['-updated_at'],
            },
        ),
    ]
