# Generated by Django 4.2.20 on 2025-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
