# Generated by Django 4.2.20 on 2025-06-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_user_email_notifications_user_in_app_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
