# Generated by Django 4.2.20 on 2025-06-28 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0014_useragreement'),
        ('User', '0017_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreementAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_title', models.CharField(max_length=255)),
                ('agreement_content', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masteradmin.useragreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptances', to='User.user')),
            ],
            options={
                'verbose_name': 'User Agreement Acceptance',
                'verbose_name_plural': 'User Agreement Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
