# Generated by Django 4.2.20 on 2025-06-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_useragreementacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
