# Generated by Django 4.2.20 on 2025-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apps_is_temporarily_disabled'),
        ('User', '0019_user_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='excluded_apps',
            field=models.ManyToManyField(blank=True, help_text='Apps that the user has chosen to exclude from their plan.', to='app.apps'),
        ),
    ]
