# Generated by Django 4.2.20 on 2025-06-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apps_url_keyword'),
        ('User', '0020_user_excluded_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserAppCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.IntegerField(blank=True, help_text='Null or -1 for unlimited credits.', null=True)),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_credits', to='User.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'app')},
            },
        ),
    ]
