# Generated by Django 4.2.20 on 2025-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_user_is_profile_complete_userappcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
