# Generated by Django 4.2.20 on 2025-06-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('masteradmin', '0014_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='masteradmin.coupons'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half_Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=15),
        ),
        migrations.CreateModel(
            name='AppSubscriptionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('Limited', 'Limited'), ('Unlimited', 'Unlimited')], default='Limited', max_length=10)),
                ('credits', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apps')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_limits', to='masteradmin.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'app')},
            },
        ),
    ]
