# Generated by Django 4.2.20 on 2025-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0015_subscription_coupons_alter_subscription_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragreement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
